name: Render Keep Alive

on:
  schedule:
    # Runs every 15 minutes (approx)
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allows manual run for testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Health Endpoint
        run: curl -I https://finance-bot-nvrn.onrender.com/health
